### ISSUE TITLE
pattern package in Python -> R

### ISSUE THREAD

**Issue by yidilozdemir** [ssalustri19/final-project-idil-sammy#1]
https://blog.rstudio.com/2018/03/26/reticulate-r-interface-to-python/

We can work with the sentiment package in python through an R interface. We will use package (https://www.clips.uantwerpen.be/pattern) pattern to analyze whole tweets and return their subjectivity and polarity ratings. This link describes how.

**Comment by ssalustri19** [comment]
aborted this plan
